# Generated by Django 6.0.3 on 2026-04-03 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonneDisparue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sexe', models.CharField(choices=[('fille_femme', 'Fille / Femme'), ('garcon_homme', 'Garçon / Homme')], max_length=20)),
                ('categorie', models.CharField(choices=[('enfant', 'Enfant'), ('femme', 'Femme'), ('homme', 'Homme'), ('personne_agee', 'Personne âgée')], max_length=20)),
                ('taille', models.CharField(blank=True, max_length=20)),
                ('teint', models.CharField(blank=True, max_length=50)),
                ('signes_particuliers', models.TextField(blank=True)),
                ('date_disparition', models.DateField()),
                ('heure_disparition', models.TimeField(blank=True, null=True)),
                ('region', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('vetements', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='disparitions/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('en_recherche', 'En recherche'), ('retrouvee', 'Retrouvée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('declarant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personne disparue',
                'verbose_name_plural': 'Personnes disparues',
                'ordering': ['-date_creation'],
            },
        ),
    ]
