# Generated by Django 6.0.3 on 2026-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disparitions', '0002_alter_personnedisparue_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnedisparue',
            name='region',
            field=models.CharField(choices=[('Adamaoua', 'Adamaoua'), ('Centre', 'Centre'), ('Est', 'Est'), ('Extreme Nord', 'Extrême-Nord'), ('Littoral', 'Littoral'), ('Nord', 'Nord'), ('Nord Ouest', 'Nord-Ouest'), ('Ouest', 'Ouest'), ('Sud', 'Sud'), ('Sud Ouest', 'Sud-Ouest')], max_length=100),
        ),
    ]
