# Generated by Django 6.1.1 on 2026-09-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disparitions', '0003_alter_personnedisparue_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnedisparue',
            name='telephone_contact',
            field=models.CharField(blank=True, help_text='Numéro joignable directement par les témoins (Orange, MTN, WhatsApp...)', max_length=30, verbose_name="Téléphone d'urgence (famille / enquêteur)"),
        ),
    ]
