# Generated by Django 6.0.3 on 2026-04-03 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disparitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_nom', models.CharField(blank=True, max_length=100)),
                ('auteur_telephone', models.CharField(max_length=20)),
                ('lieu', models.CharField(max_length=200)),
                ('date_observation', models.DateField()),
                ('message', models.TextField()),
                ('est_valide', models.BooleanField(default=False)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temoignages', to='disparitions.personnedisparue')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
